server:
  port: 9096
  servlet:
    context-path: /secret
spring:
  redirect_uri: http://127.0.0.1:9096/secret/file/getFile/
  config:
    name: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/secret_room?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 3000

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  redis:
    host: 192.168.0.102
    port: 6379
    password: 1804123028
    timeout: 3000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  mapper-locations:
    - classpath:mapper/*.xml
  logging:
    level:
      com.secret.mapper=DEBUG

wechat:
  appId: xx
  appSecret: xx
  successTemplateId: ww
  cancelTemplateId: xx
  failTemplateId: ss
  pay:
    mchId: xx
    mchKey: xx
    keyPath: xx
    timeout: 600
    payNotify: https://26188fv135.goho.co/applets/pay/back
    refund: https://26188fv135.goho.co/applets/pay/refund/back
file:
  upload:
    path: D:\images
ws:
#  allowedOrigins: *
  endpoint: /webSocketServer