server:
  port: 9096
spring:
  config:
    name: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jydb?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxxx
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  redis:
    host: 127.0.0.1
    port: 6379
    password: xxxx
    timeout: 3000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  mapper-locations:
    - classpath:mapper/*.xml

wechat:
  appId: xx
  appSecret: xx
  openId:
  isDebug: false
