server:
  port: 9096
  servlet:
    context-path: /secret
spring:
  redirect_uri: https://127.0.0.1:9096/secret/file/getFile/
  config:
    name: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/secret_room?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: xxx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 3000

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  mapper-locations:
    - classpath:mapper/*.xml
#logging.config: classpath:log4j2-spring.xml

#自动建表设置
mybatis:
  table:
    auto: update
  model:
    #扫描用于创建表的对象的包名
    pack: com.secret.model.entity
  database:
    type: mysql
wechat:
  appId: xxxx
  appSecret: xxxx
  successTemplateId: ww
  cancelTemplateId: xx
  failTemplateId: ss
file:
  upload:
    path: E:\images
ws:
#  allowedOrigins: *
  endpoint: /webSocketServer